#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    if [ -d /run/systemd/system ]; then
      systemctl stop rpgplay-server.service rpgplay-server-purge.timer >/dev/null 2>&1 || true
      if [ "$1" = remove ]; then
        systemctl disable rpgplay-server.service rpgplay-server-purge.timer >/dev/null 2>&1 || true
      fi
    fi
    ;;
esac

exit 0
