"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-23 15:31:04.731745+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rulesets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("license", sa.String(length=40), nullable=False),
        sa.Column("license_url", sa.String(length=255), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "planned", "restricted", name="rulesetstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "pack", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rulesets")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=40), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("age_gate_confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_version", sa.String(length=20), nullable=False),
        sa.Column("privacy_version", sa.String(length=20), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "characters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("ruleset_id", sa.String(length=64), nullable=False),
        sa.Column("ruleset_version", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "complete", name="characterstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("wizard_step", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("portrait_key", sa.String(length=255), nullable=True),
        sa.Column("ancestry_key", sa.String(length=64), nullable=True),
        sa.Column("ancestry_name", sa.String(length=60), nullable=True),
        sa.Column(
            "ancestry_choices",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("class_key", sa.String(length=64), nullable=True),
        sa.Column("class_name", sa.String(length=60), nullable=True),
        sa.Column("background_key", sa.String(length=64), nullable=True),
        sa.Column("background_name", sa.String(length=60), nullable=True),
        sa.Column(
            "background_bonus",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "attribute_method",
            sa.Enum(
                "standard_array",
                "point_buy",
                "roll",
                "class_preset",
                "manual",
                name="attributemethod",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "attribute_audit",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("hp_max", sa.Integer(), nullable=False),
        sa.Column("hp_current", sa.Integer(), nullable=False),
        sa.Column("hp_temp", sa.Integer(), nullable=False),
        sa.Column(
            "spell_slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "conditions", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_characters_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["ruleset_id"], ["rulesets.id"], name=op.f("fk_characters_ruleset_id_rulesets")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(op.f("ix_characters_owner_id"), "characters", ["owner_id"], unique=False)
    op.create_table(
        "content_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum("user", "character", "room", "event", name="reporttarget", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "harassment",
                "sexual",
                "hate",
                "violence",
                "spam",
                "other",
                name="reportreason",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "reviewing", "actioned", "dismissed", name="reportstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_content_reports_reporter_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_reports")),
    )
    op.create_index(op.f("ix_content_reports_reporter_id"), "content_reports", ["reporter_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pin", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("master_id", sa.Uuid(), nullable=False),
        sa.Column("ruleset_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.Enum("open", "closed", name="roomstatus", native_enum=False, length=32), nullable=False
        ),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["master_id"], ["users.id"], name=op.f("fk_rooms_master_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["ruleset_id"], ["rulesets.id"], name=op.f("fk_rooms_ruleset_id_rulesets")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
    )
    op.create_index(op.f("ix_rooms_master_id"), "rooms", ["master_id"], unique=False)
    op.create_index(
        "uq_rooms_open_pin",
        "rooms",
        ["pin"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
        sqlite_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "user_blocks",
        sa.Column("blocker_id", sa.Uuid(), nullable=False),
        sa.Column("blocked_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blocked_id"], ["users.id"], name=op.f("fk_user_blocks_blocked_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"], ["users.id"], name=op.f("fk_user_blocks_blocker_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id", name=op.f("pk_user_blocks")),
    )
    op.create_table(
        "character_abilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("uses_max", sa.Integer(), nullable=False),
        sa.Column("uses_spent", sa.Integer(), nullable=False),
        sa.Column(
            "recharge",
            sa.Enum("short_rest", "long_rest", "none", name="recharge", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_abilities_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_abilities")),
    )
    op.create_index(op.f("ix_character_abilities_character_id"), "character_abilities", ["character_id"], unique=False)
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("weight_each", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("equipped", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_inventory_items_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
    )
    op.create_index(op.f("ix_inventory_items_character_id"), "inventory_items", ["character_id"], unique=False)
    op.create_table(
        "room_members",
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.Enum("master", "player", name="roomrole", native_enum=False, length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("kicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_room_members_character_id_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_room_members_room_id_rooms"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_room_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("room_id", "user_id", name=op.f("pk_room_members")),
    )
    op.create_table(
        "session_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "dice_roll",
                "hp_change",
                "join",
                "leave",
                "rest",
                "system",
                name="sessioneventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("public", "master_only", name="visibility", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_session_events_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_session_events_character_id_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_session_events_room_id_rooms"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_events")),
    )
    op.create_index("ix_session_events_room_created", "session_events", ["room_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_events_room_created", table_name="session_events")
    op.drop_table("session_events")
    op.drop_table("room_members")
    op.drop_index(op.f("ix_inventory_items_character_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_character_abilities_character_id"), table_name="character_abilities")
    op.drop_table("character_abilities")
    op.drop_table("user_blocks")
    op.drop_index(
        "uq_rooms_open_pin",
        table_name="rooms",
        postgresql_where=sa.text("status = 'open'"),
        sqlite_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_rooms_master_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_content_reports_reporter_id"), table_name="content_reports")
    op.drop_table("content_reports")
    op.drop_index(op.f("ix_characters_owner_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("rulesets")
    # ### end Alembic commands ###
